import { GRAMMAR_QUESTIONS_BY_GRADE } from './grammarData';
import { LISTENING_QUESTIONS_BY_GRADE } from './listeningData';
import { SPEAKING_QUESTIONS_BY_GRADE } from './speakingData';
import { WRITING_QUESTIONS_BY_GRADE } from './writingData';
import { READING_QUESTIONS_BY_GRADE } from './readingData';

export {
  GRAMMAR_QUESTIONS_BY_GRADE,
  LISTENING_QUESTIONS_BY_GRADE,
  SPEAKING_QUESTIONS_BY_GRADE,
  WRITING_QUESTIONS_BY_GRADE,
  READING_QUESTIONS_BY_GRADE,
};

// Dữ liệu mặc định nếu không truyền grade (mặc định grade 6)
export const INITIAL_QUESTIONS = GRAMMAR_QUESTIONS_BY_GRADE[6];
export const INITIAL_LISTENING_QUESTIONS = LISTENING_QUESTIONS_BY_GRADE[6];
export const INITIAL_SPEAKING_QUESTIONS = SPEAKING_QUESTIONS_BY_GRADE[6];
export const INITIAL_WRITING_QUESTIONS = WRITING_QUESTIONS_BY_GRADE[6];
